const API_URL = "https://sozlarjadvalii-d30a85c91d78.herokuapp.com/api/controller/Get-All-Words";

export async function getAllWords() {
  const res = await fetch(API_URL);

  // fetch won't throw error on 400 errors (e.g. when URL is wrong), so we need to do it manually. This will then go into the catch block, where the message is set
  if (!res.ok) throw Error("Failed getting menu");

  const data = await res.json();
  return data;
}

// export async function getOrder(id) {
//   const res = await fetch(`${API_URL}/order/${id}`);
//   if (!res.ok) throw Error(`Couldn't find order #${id}`);

//   const { data } = await res.json();
//   return data;
// }

// export async function createOrder(newOrder) {
//   try {
//     const res = await fetch(`${API_URL}/order`, {
//       method: "POST",
//       body: JSON.stringify(newOrder),
//       headers: {
//         "Content-Type": "application/json",
//       },
//     });

//     if (!res.ok) throw Error();
//     const { data } = await res.json();
//     return data;
//   } catch {
//     throw new Error("Failed creating your order");
//   }
// }

// export async function updateOrder(id, updateObj) {
//   try {
//     const res = await fetch(`${API_URL}/order/${id}`, {
//       method: "PATCH",
//       body: JSON.stringify(updateObj),
//       headers: {
//         "Content-Type": "application/json",
//       },
//     });

//     if (!res.ok) throw Error();
//     // We don't need the data, so we don't return anything
//   } catch (err) {
//     throw Error("Failed updating your order");
//   }
// }


export function getAllData() {
  const data = [
    {
      yordamchiSoz: "-a   I",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "qo'shimchasimon",
      uslubiyXoslanishi: "so'roq",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "- Qizim, bugun mehmonlaringni Sultonxonlarnikiga olib chiqasan-a?  Cho'lpon, Kecha va kunduz.",
    },
    {
      yordamchiSoz: "-a   II",
      turkumi: "bog'lovchi",
      xalqaroTegi: "bog'l",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "qo'shimchasimon",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "yuklama",
      yordamchiSozVaOlinganManba: '"Xo\'sh, va\'dang qancha? - "Qirq sentnerdan". "A qizlar-chi?" - "Yuz". Oybek, Oltin vodiydan shabadalar.',
    },
    {
      yordamchiSoz: "agar I",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "bog'lovchi",
      yordamchiSozVaOlinganManba: "Agar u kelgan bo'lsa, o'zini bildirgan bo'lar edi.Oybek. Tanlangan asarlar",
    },
    {
      yordamchiSoz: "agar II",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "yuklama",
      yordamchiSozVaOlinganManba: "Agar arqondan qo'llari chiqib ketsa, to tuman tarqalguncha yo'l topa olmay sarson bo'lib yuraveradilar.S.Ahmad.",
    },
    {
      yordamchiSoz: "agarchi",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Agarchi sensizin sabr aylamak, ey yor, mushkuldur. Z.M.Bobur.",
    },
    {
      yordamchiSoz: "agarda",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Agarda avval boshdanoq kattalarning gapiga quloq tutganimizda bunday ayanchli holga tushmasdik.",
    },
    {
      yordamchiSoz: "ayni",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "olmosh",
      yordamchiSozVaOlinganManba: "Chol ayni savolni Matyunusga ham berdi... M.Ismoiliy, Farg'ona tong otguncha.",
    },
    {
      yordamchiSoz: "aynan",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Otasining aynan o'zi.",
    },
    {
      yordamchiSoz: "ammo",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "sof.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Mayli , siz yashirdingiz. Ammo men yashirmayman.",
    },
    {
      yordamchiSoz: "ammo II",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "bog'lovchi",
      yordamchiSozVaOlinganManba: "Ammo rossa vaqtida kelibmiz-da.",
    },
    {
      yordamchiSoz: "ammo-lekin",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yuk",
      shakli: "so'z shaklda",
      manoTuri: "ta'kid",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: 'Ammo-lekin Esh qattiq ishladi.S.Ahmad."Ufq"',
    },
    {
      yordamchiSoz: "ana",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yuk",
      shakli: "so'z shaklda",
      manoTuri: "ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "olmosh",
      yordamchiSozVaOlinganManba: "Ana ko'rdingmi, nima bo'ldi? Ana endi, sendan keladigan ish shu-da. S.Ahmad.Ufq.",
    },
    {
      yordamchiSoz: "aqalli",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Nigoraning beparvogina qaytargan javobi yuzida aqalli qilday ham o'zgarish sezilmagani Xo'jabekovning g'azabini qaynatdi.S.Anorboyev, Oqsoy.",
    },
    {
      yordamchiSoz: "arafasida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt,zamon",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Navro'z arafasida keksalar oq kiyim tayyorlashadi, yoshlar rang-barang gulli ko'ylaklar tiktirishadi.Saodat.",
    },
    {
      yordamchiSoz: "aro",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Oh urib maydon aro Rustam kabi solsam urush. Nurali",
    },
    {
      yordamchiSoz: "aslo",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "inkor",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Onam go'rida tinch yotsin desanglar, Qumrini aslo yolg;izlatib qo'ymanglar. S.Ahmad, Qorako'z majnun.",
    },
    {
      yordamchiSoz: "asti",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "inkor",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Vatan ishqida yongan qalb, Bilingki, asti xor bo'lmas. E.Vohidov, Ishq savdosi.",
    },
    {
      yordamchiSoz: "asnoda",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "vaqt,payt",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Shu asnoda Risolat Rustamga baqamti kelib, uning chap kifti bilan tirsagi o'rtasidan ushladi. Q.Kenja, Toshqin",
    },
    {
      yordamchiSoz: "asnodan",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "",
      uslubiyXoslanishi: "vaqt,payt",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Shu asnodan boshqacha yo'l tutamiz.Gazetadan",
    },
    {
      yordamchiSoz: "asosan",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab, asos",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Tegishli buyruqqa asosan ishdan bo'shatildi. Gazetadan",
    },
    {
      yordamchiSoz: "asosiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab, asos",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Muhabbatdan ko'ra bir-birini tushunish asosiga qurilgan oila mustahkamroqdir. Chunki…",
    },
    {
      yordamchiSoz: "asosida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab, asos",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Dori-darmonni shifokor yo'riqnomasi asosida ishlating.Gazetadan",
    },
    {
      yordamchiSoz: "atab",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "atalganlik",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "O'zbek oyimning qutidor, Oftob oyim va Oysha kampirga atab tiktirgan sarupolari ham bitdi.A.Qodiriy.O'tkan kunlar.",
    },
    {
      yordamchiSoz: "atrofiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Notiqning ma'ruzasi mavzuning atrofiga ham yaqinlashmadi.",
    },
    {
      yordamchiSoz: "atrofida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "chama",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Shu  ikki fikr atrofida munozara juda qizib ketdi. A.Qahhor.Qo'shchinor chiroqlari.",
    },
    {
      yordamchiSoz: "atigi",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Qozi pochcham tush ko'rsalar, atigi  uchtagina qolgan so'yloq",
    },
    {
      yordamchiSoz: "avval",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Mana so'nggi xotira: ikki yarim yil avval mehribon ona uni shaharga uzatdi. Oybek. Tanlangan asarlar.",
    },
    {
      yordamchiSoz: "avvalroq",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Dadamni bir yilga qamashgan ekan, boshliqlari insofliroq bo'lsa kerak, oilangda bayram qila qol, deb muddatidan avvalroq bo'shatib yuborishibdi…A.Obidjon, Oddiy ayriliq haqida ertak.",
    },
    {
      yordamchiSoz: "ayniqsa",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "so'zlashuv va kitobiy",
      sofTurkumi: "modal so'z",
      yordamchiSozVaOlinganManba: "Atom energiyasidan foydalanishning istiqboli ayniqsa kengdir",
    },
    {
      yordamchiSoz: "axir",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "modal so'z",
      yordamchiSozVaOlinganManba: "Axir men muhabbatimni ehtiyot qilolmagan, yolg'iz yaxshi ko'rish bilan kifoyalanib yurgan odamman-ku!O'.Hoshimov, Xayollarga bo'laman tutqun.",
    },
    {
      yordamchiSoz: "bale",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "tasdiq yuklamasi",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Furqatiy qosh-u ko'zingdan fitnalar ko'rdi, bale..Furqat",
    },
    {
      yordamchiSoz: "balki",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "modal so'z",
      yordamchiSozVaOlinganManba: "U sodiq qul, balki undan battar odam edi.Oybek. Tanlangan asarlar.",
    },
    {
      yordamchiSoz: "balkim",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "modal so'z",
      yordamchiSozVaOlinganManba: "Qalbi pok ishq ahlining vijdoni, balkim jonidir.Habibiy",
    },
    {
      yordamchiSoz: "balli",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yuk",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "undov",
      yordamchiSozVaOlinganManba: "- Ko'chada sen bilan yetaklashib yuradigan xotinga balli-yey! - dedi Zumrad.S.Siyoyev, Otliq ayol.",
    },
    {
      yordamchiSoz: "bamisoli",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Aql va madaniyat, haq va adolat bamisoli oftob: uni to'sish va yo'qotish mumkin emas. A.Hakimov. Ilon izidan",
    },
    {
      yordamchiSoz: "baravariga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "kitobiy",
      uslubiyXoslanishi: "ravish",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Bir tanob yerdan oltmish pud paxta olib, naqd pul baravariga hukumatga topshiradi. A.Qodiriy, G'irvonlik Mallavoy.",
    },
    {
      yordamchiSoz: "baravarida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "tenglik, birgalik betaraf",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "sifat, ravish",
      yordamchiSozVaOlinganManba: "Shu maqola baravarida ma'lum qilamanki, sud Ibrohimov mendan pora so'ragani yolg'on. A.Qahhor, Sarob",
    },
    {
      yordamchiSoz: "badaliga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "evaz",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Ammo buning badaliga, yuqoridagi mollardan tashqari bir tanob yerdan oltmish pud paxta olib. A.Qodiriy, G'irvonlik Mallavoy.",
    },
    {
      yordamchiSoz: "badalida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "vaqt",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Ikki yil badalida otamning topib-tutib to'lagani qarzining foydasinigina qoplay oldi. F.Rasul, Adolat.",
    },
    {
      yordamchiSoz: "bad'az",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "vaqt",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Bizdan ba'daz salom, dil mehri bilan, Yurtdoshlik quvonchin zo'r mehri bilan. G'.G'ulom",
    },
    {
      yordamchiSoz: "ba'zan",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Ba'zan Qoratoyning ishxonasida, ba'zan choyxonada tunab yurdi. Oybek. Tanlangan asarlar.",
    },
    {
      yordamchiSoz: "basharti",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Basharti arizada bitilgan gaplar rost bo'lganda ham seni ayblashga ko'nglim bo'lmaydi. Cho'lpon. \"Kecha va kunduz\"",
    },
    {
      yordamchiSoz: "bag'oyat",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Sirsiz hayot senga bag'oyat mushkul, Yuragingda yashar itoatli qul. E.Vohidov, Umrim daryosi.",
    },
    {
      yordamchiSoz: "baayni",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Xullasi kalom, bu birinchi uylanishim anvoyi tashvish va to'polon birlan baayni tushdagidek bo'lib o'tdi. A.Qodiriy, G'irvonlik Mallavoy.",
    },
    {
      yordamchiSoz: "-bek",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "erkalash",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Anvarbek, sal pastga tushing, burningizdan naryog'ini ko'zingiz ko'rmay qolyapti-ku! So'zlashuvdan",
    },
    {
      yordamchiSoz: "beri",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Institutga kirgandek beri Kozimjon orqasidan soyadek ergashib yuribdi. T.Ashurov, Oq ot.",
    },
    {
      yordamchiSoz: "beriga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Qamalgan kunimdan beriga undan xabarim yo'q taqsir! A.Qodiriy, O'tkan kunlar.",
    },
    {
      yordamchiSoz: "berida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Maston yuqoriroqqa chiqib, dasht tomonga qaradi. Ufqdan berida o'rgimchakday o'rmalab arava kelar edi. A.Qahhor, Maston.",
    },
    {
      yordamchiSoz: "bila",
      turkumi: "ko'makchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "birgalik",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Bu shaklu shamoyil bila xud huru pariysen, Kim, jinsi bashar ichra bu miqdor topilmas. Z.M.Bobur.",
    },
    {
      yordamchiSoz: "bilan I",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "tenglik",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Bular ko'zdan g'oyib bo'lgandan keyin, Kanizak bilan Siddiqjon butaning orqasidan chiqishdi. A.Qahhor, Qo'shchinor chiroqlari.",
    },
    {
      yordamchiSoz: "bilan II",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "birgalik",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Oshning ta'mi tuz bilan, odam ta'mi so'z bilan. Maqol",
    },
    {
      yordamchiSoz: "binoan",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "asos",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Qulluq, chaqirganingizga binoan xizmatingizga keldik, nima deysiz. Luqmoni Hakim.",
    },
    {
      yordamchiSoz: "bir I",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "son",
      yordamchiSozVaOlinganManba: "Bu gapga chindan ishongan Nilufar taajjublanib, bir akasiga, bir mushukka qaradi. S.Ahmad, Yulduz.",
    },
    {
      yordamchiSoz: "bir II",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "son",
      yordamchiSozVaOlinganManba: "Hamma rozi bo'ldi, bir men rozi bo'lmadim.",
    },
    {
      yordamchiSoz: "biram",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "- Voy, shirinim-ey, rahmatli otangga o'xshab senham biram mehribonsanki, tillaring ham biram shirinki. X.To'xtaboyev, Jannati odamlar.",
    },
    {
      yordamchiSoz: "birla",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "birgalik",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Agarchi sensizin sabr aylamak, ey yor, mushkuldur, Sening birla chiqishmoqlik dag'i bisyor mushkuldur. Z.M.Bobur.",
    },
    {
      yordamchiSoz: "birgina",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "son",
      yordamchiSozVaOlinganManba: "Agar hayotimizning barcha maqsad-mazmuni oiladagi shaxsiy baxtimizdan iborat bo'lganida, shaxsiy baxtimiz birgina oiladagi muhabbatda o'z ifodasini topganda edi, unda hayot deganlari chindan ham qop-qorong'u sahroga aylanib qolgan bo'lar edi. T.Malik, Odamiylik mulki.",
    },
    {
      yordamchiSoz: "biroq",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "sof.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Garajda mashinam bor, biroq uni yurgizadigan odam yo'q. S.Ahmad. Mukammal inson suvrati.",
    },
    {
      yordamchiSoz: "birdan bir",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "son",
      yordamchiSozVaOlinganManba: "Birdan bir maqsadim: olib keting men sho'rlikni! Yoringiz bo'lmasam, cho'ringiz bo'lay. O.Yoqubov, Avlodlarga vasiyat",
    },
    {
      yordamchiSoz: "birda",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "son",
      yordamchiSozVaOlinganManba: "Birda shukr, birda fikr qildik biz.",
    },
    {
      yordamchiSoz: "bitta",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "Yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "son",
      uslubiyXoslanishi: "ayiruv-chegaralov",
      sofTurkumi: "so'zlashuv",
      yordamchiSozVaOlinganManba: "Mana, siz bitta o'zingiz o'ttiz ikkita mashinaga qarar emishsiz. A.Qahhor, Yillar.",
    },
    {
      yordamchiSoz: "bo",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "birgalik",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "- Ota - bu singlim, tabassum bilan dedi Yo'lchi, - qishloqdan olib kelganimni eshitgandingiz. Boynikida yashashini ma'qul ko'rmadim. - [Shokir ota] Yaxshi qilibsan: \"Kabutar bo kabutar, jins bo jins\" Oybek Tanlangan asarlar. O'TIL. 1-tom. 290-s.",
    },
    {
      yordamchiSoz: "bobida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "mavzu ma'nosi",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Ul qizi husn bobida yakka-yu yagona edi. Usmon baxshi Mamat o'g'li. Bo'tako'z",
    },
    {
      yordamchiSoz: "bois",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab, asos",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Mashg'ulot o'z vaqtida boshlanmagani bois talabalar xonadan chiqib ketgan edi. Gazetadan",
    },
    {
      yordamchiSoz: "boisi",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab, asos",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Xulq-atvor boisidan aziyat chekmang. Hikmatli so'z.",
    },
    {
      yordamchiSoz: "borada",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "mavzu ma'nosi",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Xuddi shu borada o'rtoq Nurmuhammedov bilan janjallashib o'tirgan edik. \"Mushtum\"",
    },
    {
      yordamchiSoz: "borasida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "mavzu ma'nosi",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "U dehqon ko'ngliga ma'qul tushgan yangi nav borasida so'zlardi. S.Mahkamov, Dehqon quvonchi.",
    },
    {
      yordamchiSoz: "bordi-yu",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Bordi-yu, ajdodida bo'lsa to'qqizga to'lganda tarlon bo'ladi. T.Murod, Ot kishnagan oqshom.",
    },
    {
      yordamchiSoz: "bor-yo'g'i",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yuk",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "jamlovchi ot",
      yordamchiSozVaOlinganManba: "Biz bor-yo'g'I uch jonmiz, uch kosa yetadi. S.Siyoyev, Yorug'lik",
    },
    {
      yordamchiSoz: "bori",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Aytadigan gapingning bori shumi? So'zlashuvdan.",
    },
    {
      yordamchiSoz: "boshiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Bitar ishning boshiga, yaxshi kelar qoshiga. Maqol.",
    },
    {
      yordamchiSoz: "boshida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Ayollar ko'prik boshida chapak chalib, tizzalarini urib chinqirishdi. Oybek, Tanlangan asarlar.",
    },

    {
      yordamchiSoz: "boshidan",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot,sifat",
      yordamchiSozVaOlinganManba: "Bitar ishning boshiga, yaxshi kelar qoshiga. Maqol.",
    },
    {
      yordamchiSoz: "boshlab",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Shu kundan boshlab u ham raisning oldida to'ng'illab gapiradigan bo'lib qoldi. \"Mushtum\".",
    },
    {
      yordamchiSoz: "boshqa",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "- Menga qolsa, o'rtada shundan boshqa hech gap yo'q, o'g'lim - dedi [hoji]. A.Qodiriy, O'tkan kunlar.",
    },
    {
      yordamchiSoz: "bog'liq",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "tegishlilik",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "sifat",
      yordamchiSozVaOlinganManba: "Ishimizning aniq raqamlarga bo'gliq sahifalarida xatoliklar bo'lmasligi lozim. Gazetadan.",
    },
    {
      yordamchiSoz: "buyon",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Ko'p yillardan buyon niyat va orzularda, xayol kengliklarida bo'y ko'rsatgan go'zal asarni yaratish uchun barcha hozirliklar ko'rib bo'lingan edi go'yo. I.Sulton, Alisher Navoiy.",
    },
    {
      yordamchiSoz: "burun",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Men-chi? Men bu yerda undan burun o'lib qolaman-ku. O.Yoqubov, Bir koshona sirlari.",
    },
    {
      yordamchiSoz: "bo'lsa",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Haqqush bo'lsa to'xtovsiz sayrar, yoz shabadasida uning ovozi goh sekin, goh baralla eshitilardi. O'Hoshimov, Qalbingga quloq sol.",
    },
    {
      yordamchiSoz: "bo'lgani",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "- Xurshid, jon do'stim, hech narsa qilib qo'yganim yo'q, uyimda bir kun tinchgina o'tiraman degan edim, bo'lgani shu, sizlar bo'lsa… A.A'zam, Nima qilib qo'ygan ekanman.",
    },
    {
      yordamchiSoz: "bo'yi",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Shu bo'yi bir hafta Me'mor uydan chiqmadi. Mirmuhsin, Me'mor.",
    },
    {
      yordamchiSoz: "bo'yiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Rixsi xola nafasini rostlash uchun ariq bo'yiga cho'nqaydi. S.Zununova, Olov",
    },
    {
      yordamchiSoz: "bo'yida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Salomatligini sovurayotgan odam ariq bo'yida suv qadrini bilmay o'tirgan kishiga o'xshaydi. Gazetadan.",
    },
    {
      yordamchiSoz: "bo'yidan",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Ularning yo'li kanal bo'yidan o'tardi.",
    },
    {
      yordamchiSoz: "bo`yicha",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "tegishlilik",
      uslubiyXoslanishi: "rasmiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Savodsizlikni tugatish bo'yicha o'qish bir qadar yo'lga tushib qoldi. K.Yashin. Hamza",
    },
    {
      yordamchiSoz: "bo'lak",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Insof bilan aytganda, do'konda odamning jonidan bo'lak hamma narsa bor. O'.Hoshimov, Tushda kechgan umrlar.",
    },
    {
      yordamchiSoz: "bo`ylab",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Oyoqqa yelimday yopishayotgan so'qmoq bo'ylab ketishdi. O'.Hoshimov. Qalbingga quloq sol",
    },
    {
      yordamchiSoz: " -da I",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Baraka topkur, zap fayzli ayol-da, Bemorning og'rig'ini ikki og'iz so'z bilan tuzatvoradi-ya. S.Ahmad, Azroil o'tgan yo'llarda.",
    },
    {
      yordamchiSoz: " -da II",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "so'roq",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Sartarosh bo'lay debsiz-da, a? E.Raimov, Ajab qishloq.",
    },

    {
      yordamchiSoz: "-da III",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "qo'shimchasimon",
      manoTuri: "biriktiruv",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "yuklama",
      yordamchiSozVaOlinganManba: "Yodgor yon-veriga alanglab, bo'shab qolganini ko'rdi-da, darrov o'rnidan turdi. O'.Hoshimov, Qalbingga quloq sol.",
    },
    {
      yordamchiSoz: "-da IV",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "qo'shimchasimon",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "yuklama",
      yordamchiSozVaOlinganManba: "Bu hukm garchi boshqa bir paytda qaror topgan taomil mezoniga muvofiq kelmasa-da, shu topda adolatli va insonparvar edi. N.Eshonqul, Urush odamlari.",
    },
    {
      yordamchiSoz: "dam",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Suv dam oqizib ketadi, dam chetga otadi. S.Ahmad, Ufq.",
    },
    {
      yordamchiSoz: "dastidan",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Rost, akasi uning dastidan qamaldi",
    },
    {
      yordamchiSoz: "darajada",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "ot",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Sovuq shu darajada ediki, biron pana joyga yashirinmasa chidab bo'lmas edi. S.Ahmad, Kiprikda qolgan tong.",
    },
    {
      yordamchiSoz: "davomiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Shuncha yaxshiliklaringiz davomiga meni maqtab ham qo'yganingizdan xijolatdaman. Gazetadan",
    },
    {
      yordamchiSoz: "davomida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Saodatxon ikkinchi chorak davomida qilinadigan ishlarni batafsil so'zlab berdi. S.Zununova. Olov.",
    },
    {
      yordamchiSoz: "dim (shv)",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "inkor",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "sifat",
      yordamchiSozVaOlinganManba: "Ichkari kir, yota bergin joyingga, dim ularga qaray ko'rma, chirog'im. 'Ravshan' [aslo, sira ma'nolarida]",
    },
    {
      yordamchiSoz: "deb I",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "sabab-maqsad",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Har kishi ter to'kib qiladi mehnat, xalqimning turmushi obod bo'lsin deb. 'G'ulom'",
    },
    {
      yordamchiSoz: "deb",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "atalganlik",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Yorimga deb qiyiq oldim -  bezakdor. Xalq qo'shiqlari.",
    },
    {
      yordamchiSoz: "-dek",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "qo'shimchasimon",
      manoTuri: "o'xshatish-qiyoslash",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Ul nasihat uchun og'iz ochsa vujudim erib ketgandek va bir turluk uxlab huzurlangandek. A.Qodiriy, O'tkan kunlar.",
    },
    {
      yordamchiSoz: "-day",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "qo'shimchasimon",
      manoTuri: "o'xshatish-qiyoslash",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Anavi to'ng'ich akangizning qo'ylari bo'lmaydi! Bari o'ziday kaltafahm! T. Murod, Ot kishnagan oqshom.",
    },
    {
      yordamchiSoz: "-dayin",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "qo'shimchasimon",
      manoTuri: "o'xshatish-qiyoslash",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Yoq dema so'zlarimga, Yo'q ketma o'zgalarga, Yo'q go'zal sendayin olam ichra, ishon. Qo'shiqdan",
    },
    {
      yordamchiSoz: "deya",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Yurt deya qon kechdilar ne tilla boshlar. Xalq qo'shiqlari",
    },
    {
      yordamchiSoz: "deganda",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Ikki yil deganda uni o'shatdagi sahroda yo'qolganini aytishdi. O'.Umarbekov, Ota va o'g'il.",
    },
    {
      yordamchiSoz: "-dir",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "gumon",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: " -Qazisan, qartasan, axir  aslingga tortasan, - dedi kampir omborni qulflayotib, - … Uvada, isliqi to'n, chilvir belbog'ning xumorisi tutgandir! A.Qahhor, Qo'shchinor chiroqlari.",
    },
    {
      yordamchiSoz: "dovur",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "chegara",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Tongga dovur soz bilan, Qo'shiq aytdim sen uchun. Folklor",
    },
    {
      yordamchiSoz: "doir",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "tegishlilik",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Jaloliddin buvisi bilan salom-alik, hol-ahvol so'rashardi-yu, mudofaa va davlat ishlariga doir biron gap aytmasdi. Mirmuhsin, Temur Malik.",
    },
    {
      yordamchiSoz: "-e",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "E, bor-e, tozza boshimni qotirding! So'zlashuvdan",
    },
    {
      yordamchiSoz: "evaziga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Zaruriy bir ishni ado etayotgani evaziga siylov olayotganini, balki, it ham his qilar…U.Hamdam, Muvozanat.",
    },
    {
      yordamchiSoz: "-ey",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Qayerdanam ko'rdim-ey, yuraklarim yondi-yey. Folklor",
    },
    {
      yordamchiSoz: "deb",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab-maqsad",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Yorimga deb qiyiq oldim -  bezakdor. Xalq qo'shiqlari.",
    },
    {
      yordamchiSoz: "-dek",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "qo'shimchasimon",
      manoTuri: "o'xshatish-qiyoslash",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Ul nasihat uchun og'iz ochsa vujudim erib ketgandek va bir turluk uxlab huzurlangandek. A.Qodiriy, O'tkan kunlar.",
    },
    {
      yordamchiSoz: "-day",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "qo'shimchasimon",
      manoTuri: "o'xshatish-qiyoslash",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Anavi to'ng'ich akangizning qo'ylari bo'lmaydi! Bari o'ziday kaltafahm! T. Murod, Ot kishnagan oqshom.",
    },
    {
      yordamchiSoz: "-dayin",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "qo'shimchasimon",
      manoTuri: "o'xshatish-qiyoslash",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Yoq dema so'zlarimga, Yo'q ketma o'zgalarga, Yo'q go'zal sendayin olam ichra, ishon. Qo'shiqdan",
    },
    {
      yordamchiSoz: "deya",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Yurt deya qon kechdilar ne tilla boshlar. Xalq qo'shiqlari",
    },
    {
      yordamchiSoz: "deganda",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "fe'l",
      yordamchiSozVaOlinganManba: "Ikki yil deganda uni o'shatdagi sahroda yo'qolganini aytishdi. O'.Umarbekov, Ota va o'g'il.",
    },
    {
      yordamchiSoz: "-dir",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "gumon",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: " -Qazisan, qartasan, axir  aslingga tortasan, - dedi kampir omborni qulflayotib, - … Uvada, isliqi to'n, chilvir belbog'ning xumorisi tutgandir! A.Qahhor, Qo'shchinor chiroqlari.",
    },
    {
      yordamchiSoz: "dovur",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "chegara",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Tongga dovur soz bilan, Qo'shiq aytdim sen uchun. Folklor",
    },
    {
      yordamchiSoz: "doir",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "tegishlilik",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Jaloliddin buvisi bilan salom-alik, hol-ahvol so'rashardi-yu, mudofaa va davlat ishlariga doir biron gap aytmasdi. Mirmuhsin, Temur Malik.",
    },
    {
      yordamchiSoz: "-e",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "E, bor-e, tozza boshimni qotirding! So'zlashuvdan",
    },
    {
      yordamchiSoz: "evaziga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Zaruriy bir ishni ado etayotgani evaziga siylov olayotganini, balki, it ham his qilar…U.Hamdam, Muvozanat.",
    },
    {
      yordamchiSoz: "-ey",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Qayerdanam ko'rdim-ey, yuraklarim yondi-yey. Folklor",
    },
    {
      yordamchiSoz: "ha II",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "tasdiq yuklamasi",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Ha, rost, bemorlarning ko'pi har yerdan kelgan odamlar. S.Karomatov, Oltin qum.",
    },
    {
      yordamchiSoz: "hali",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Voy sharmandalar, hali qochirib yubordik denglar-a.N.Fozilov, Diydor. Oshni damlab hali o'tiribman, hali o'tiribman. A.Qahhor, qoshchinor chiroqlari.",
    },
    {
      yordamchiSoz: "hali",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "- Farg'onaga borgunimizcha hali Shukrullo, hali Mirmuhsinning tanishlari topilaversa, bu yaqinda manzilga yetolmaymiz, - deb Said Ahmad hazillashdi. Shukrullo. Javohirlar sandig'i.",
    },
    {
      yordamchiSoz: "ham",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Birovning aybiga kulmagin zinhor, Sening ham aybingga kuluvchilar bor.Maqol",
    },
    {
      yordamchiSoz: "ham",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "yuklama",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Bitibdur besh ravot ham uchta hammom. Uyg'un va Izzat Sulton, Alisher Navoiy.",
    },
    {
      yordamchiSoz: "hamda",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "sof.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "biriktiruv",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Chuvrindi uyga qaytgunicha ham bo'lib o'tgan suhbatlar mag'zini chaqishga harakat qilib, \"Qanoti bor har qanday maxluq ham erkin hamda baland parevoz qila olmaydi\", degan haqiqatga ishondi. T.Malik, Shaytanat",
    },
    {
      yordamchiSoz: "haqda",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "mavzu ma'nosi",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Bu haqda sahifamizning keyingi sonlarida ma'lumot beramiz. Gazetadan",
    },
    {
      yordamchiSoz: "haqida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "mavzu ma'nosi",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Biz Usmon aka bilan o'zimizning ishlarimiz, kuzgi sabzavot, yangi ochilmoqchi bo'lgan yer va boshqa ishlar haqida gaplashdik.O'.Umarbekov, Sevgim-sevgilim.",
    },
    {
      yordamchiSoz: "haqidagi",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "betaraf",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Sharif Namozovni qamash, qamoqdan chiqarish haqidagi qog'ozlarda mening imzom yo'q edi. T.Malik, Shaytanat.",
    },
    {
      yordamchiSoz: "haqiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "mavzu ma'nosi",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Mehnati haqiga olingan narsalarni nopok insonlarga bergisi kelmadi.",
    },
    {
      yordamchiSoz: "haqimda",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "so'zlashuv",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Men haqimda yolg'onlar aytishdi senga… Xalq qo'shiqlari",
    },
    {
      yordamchiSoz: "hatto",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Uyda hamma narsa unga yot hatto onasi ham begona kabi. Oybek, Tanlangan asarlar.",
    },
    {
      yordamchiSoz: "hargiz",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "inkor",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Aqlsiz odamlar bilan hargiz do'st bo'lmagil. T.Malik, Odamiylik mulki.",
    },
    {
      yordamchiSoz: "hattoki",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Biri - doktor, biri -hamshira, Uchsa hamki hattoki o'qlar, har jangchining yarasin bog'lar. H.Po'lat.",
    },
    {
      yordamchiSoz: "hech",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "inkor",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Noqulay ahvolda iljayib, unga razm soldim. Hech o'zgarmabdi. O'.Hoshimov, Hikoyalar.",
    },
    {
      yordamchiSoz: "holda",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "holat",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Imom yerga qaragan holda boshini qimirlatib qo'ydi. A.Qodiriy, Mehrobdan chayon.",
    },
    {
      yordamchiSoz: "hisobiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Xuddi boshqalarning erki hisobiga erkalik qilayotgandek. A.A'zam, bu kunning davomi.",
    },
    {
      yordamchiSoz: "holbuki",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "sof.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov ",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Shag'irlaydi betinim daryo, Shag'irlaydi vahm to'lgan jar,…Holbuki, tun - bunda odatda,Butun borliq uxlarday sokin.H.Olimjon, Holbuki, tun.",
    },
    {
      yordamchiSoz: "ila",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "sof.bog'l",
      sofvazifaDosh: "birgalik",
      shakli: "so'z shaklda",
      manoTuri: "badiiy",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "A'yonlarimiz amiralmuslimin ila bo'lak qo'rboshilar bilan baqamti bo'lmoq harakatida Farg'onada qolganlar. T.Malik, Savohil.",
    },
    {
      yordamchiSoz: "ilgari",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "ravish",
      yordamchiSozVaOlinganManba: "Yo'qolmasdan ilgari bormidi?Qanaqa ho'kiz edi? - Ola ho'kiz… A.Qahhor, O'g'ri.",
    },
    {
      yordamchiSoz: "ichra",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "",
      sofTurkumi: "badiiy",
      yordamchiSozVaOlinganManba: "Yovni ko'rsang she'r singari yurish qil, maydon ichra urush qil, Fozil shoir.",
    },
    {
      yordamchiSoz: "ichiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-payt",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Oltinchi bor hujum qildi dushman yana kuch to'plab, Tog' ichiga yashirindi chorasiz isyonkorlar. O'.Umarbekov, Gayduk qizi.",
    },

    {
      yordamchiSoz: "ko'm-",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Dilni yayratadi ko'm-ko'k maysalar. Qo'shiqdan",
    },
    {
      yordamchiSoz: "-la I",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "sof.ko'm",
      shakli: "qo'shimchasimon",
      manoTuri: "birgalik",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Oy shu'lasi-la munavvar manzil bir zumda chayqaldi. M.Ismoiliy. Farg'ona tong otguncha.",
    },
    {
      yordamchiSoz: "-la II",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ko'makchi",
      yordamchiSozVaOlinganManba: "Kelib-la ketdi.",
    },
    {
      yordamchiSoz: "lang",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "sifat",
      yordamchiSozVaOlinganManba: "Qizlar yetaklashib lang ochiq darvozadan to'g'ri kirib bordilar. A.Muxtor, Opa-singillar.",
    },
    {
      yordamchiSoz: "labbay",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "so'roq",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "undov",
      yordamchiSozVaOlinganManba: "Dunyoda kampirlarning duolarini olaylik-da, labbay? Shukrullo, Javohirlar sandig'i.",
    },
    {
      yordamchiSoz: "labiga",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Berdiyor suv labiga cho'nqayib, qo'lini chaydi, belbog'iga artib kelib, akasiga uzatdi. Sh. Xolmirzayev, Biz kecha qolib yuramiz.",
    },
    {
      yordamchiSoz: "lekin",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "sof.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Ko'nglingga qara, bolam! Lekin uylansang shunday birovini topib xotin qilginki, sira-sira joningga tegmasin. E.A'zam. Jannat o'zi qaydadir.",
    },
    {
      yordamchiSoz: "lek",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "sof.bog'l",
      shakli: "so'z shaklda",
      manoTuri: "zidlov",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Lek ko'zga ko'rinmas bugungi yovlar, kiyganday sehrli do'ppi yo qalpoq. Sh.Rahmon, Loda hazrati oliylariga.",
    },
    {
      yordamchiSoz: "liq",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Ikkinchi otdagi katta xurjunning ikki ko'zi liq to'la tanga edi. A.Qodiriy, O'tkan kunlar.",
    },
    {
      yordamchiSoz: "lim",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Xilma-xil, rang-barang, qimmatbaho meva-chevalar bilan lim to'lgan patnislar ketma-ket yetkazilib turildi. Oybek, Tanlangan asarlar.",
    },
    {
      yordamchiSoz: "loaqal",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ta'kid",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Shu to'rt devor ichra qon yutib, behad zahmat chekkan singlingizga loaqal siz shafqat qilingiz. Oybek. Ulug' yo'l.",
    },
    {
      yordamchiSoz: "mabodo",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Mabodo qachondir mansabdor bo'lib qolsang, bilib qo'y: amal kursisida o'tirganingda kim eng ko'p tovoningni yalasa, kursidan tushganingda o'sha birinchi bo'lib sendan yuz o'giradi. O'.Hoshimov. \"Daftar hoshiyasidagi bitiklar\"",
    },
    {
      yordamchiSoz: "magar",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "shart",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Magar bul so'zlaringiz rost bo'lsa, baxtiqaro bibingizni tashlab ketmas edingiz, amirim! O. Yoqubov, Avlodlarga vasiyat",
    },
    {
      yordamchiSoz: "mana",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ta'kid",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "olmosh",
      yordamchiSozVaOlinganManba: "Mana, boshqarma plan bo'limida uni rosa qizartirishdi. S.Ahmad, Bosh o'g'rig'i",
    },
    {
      yordamchiSoz: "maqsadida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "maqsad",
      uslubiyXoslanishi: "betaraf",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Otabek bilan birga choy ichish maqsadida, ertalab Oybadoqning damlangan choyiga bormay, Otabekning uyg'onishini kutib yurdi. A.Qodiriy, O'tkan kunlar.",
    },
    {
      yordamchiSoz: "-mi",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "qo'shimchasimon",
      manoTuri: "so'roq",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Mumkinmi, aytgin axir? Bu ish yaramas taqir. Q.Muhammadiy",
    },
    {
      yordamchiSoz: "-mi",
      turkumi: "bog'lovchi",
      xalqaroTegi: "conj",
      ozbekchaTegi: "bog'l",
      sofvazifaDosh: "vaz.bog'l",
      shakli: "qo'shimchasimon",
      manoTuri: "ayiruv-chegaralov",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "yuklama",
      yordamchiSozVaOlinganManba: "Yomg'irdanmi, terdanmi butun badani shalobbo ho'l. A.Muxtor, Chinor.",
    },
    {
      yordamchiSoz: "miyonasida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "payt",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "sifat",
      yordamchiSozVaOlinganManba: "Hamma ish bitganda, ikki kun miyonasida, yeng ichida nikoh o'tkazmoqchi edik. Oybek, Tanlangan asarlar.",
    },

    {
      yordamchiSoz: "misli",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Qobil farzand ota-onasi uchun misli gavhar bo'lsa, noqobil farzand ular bo'ynini bo'g'ib turuvchi misli ilondir, deydilar. T.Malik.Jinoyatning uzun yo'li.",
    },
    {
      yordamchiSoz: "misol",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Ishorani payqagan qiz darhol turib choyshabga o'randi-da, arazlagan misol g'amzali bir qarash qilib, sharpasizgina o'sha yoqqa chiqib bekindi. E.A'zam, Shovqin.",
    },
    {
      yordamchiSoz: "misoli",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "vaz.yukl",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Ota qarg'ishi misoli o'q - u oxiratda emas, shu dunyoning o'zida nishonga tegadi. S.Ahmad, Sarob",
    },
    {
      yordamchiSoz: "mos",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "holat",
      uslubiyXoslanishi: "kitobiy",
      sofTurkumi: "sifat",
      yordamchiSozVaOlinganManba: "Har tomondan vit-vit, chig'i-chig'I deb sayragan qushlarning turli qo'shiqlari soyning nashasiga mos bir muzika hosil qilgan. P.Tursun, O'qituvchi.",
    },
    {
      yordamchiSoz: "monand",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "sifat",
      yordamchiSozVaOlinganManba: "Qotillik ham qilay mayli otello monand. A.Oripov, Yillar armoni.",
    },
    {
      yordamchiSoz: "modomiki",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "ta'kid",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Modomiki ahvol shunday ekan, u kishining orzulariga quloq solishimiz kerak edi. Oybek, Tanlangan asarlar.",
    },
    {
      yordamchiSoz: "mutlaqo",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "inkor",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Uyquning-ku rasvo bo'lgani bor gap, biroq evaziga mutlaqo kutilmagan, jon-jon demoqqa arzigulik bunday tashrif va taklif! E.A'zam, Olis shahar, olis kechmishlar",
    },
    {
      yordamchiSoz: "muvofiq",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "qiyoslash",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "sifat",
      yordamchiSozVaOlinganManba: "Bu hukm garchi boshqa bir paytda qaror topgan taomil mezoniga muvofiq kelmasa-da, shu topda adolatli va insonparvar edi. N.Eshonqul, Urush odamlari.",
    },
    {
      yordamchiSoz: "na",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "inkor",
      uslubiyXoslanishi: "publisistik",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Zero, xalq shunday bir daryoyi azimki, u toshsa, na shohning qasri, na darveshning kulbasi qolur. Oybek, Navoiy",
    },
    {
      yordamchiSoz: "nari",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "o'rin-joy",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Maktabdan narimi, berimi?",
    },
    {
      yordamchiSoz: "naq",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "o'xshatish",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "- Otangizga rahmat, Yusvali tog'a! - dedi boshini qimirlatib Meli polvon. - Gapning naq onasini aytdingiz-qo'ydingiz. P.Tursun, O'qituvchi.",
    },
    {
      yordamchiSoz: "nahot",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "so'roq-taajjub",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Nahot o'g'limga o'shandoq qattiqlikni ravo ko'rsam. A.Qahhor, Qo'shchinor chiroqlari.",
    },
    {
      yordamchiSoz: "nahotki",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "so'roq-taajjub",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Aylanay, qizim, nahotki boshingga davlat qushi qo'nsa-yu, uni kaltak olib o'zing quvlasang. Hamza, Boy ila xizmatchi.",
    },
    {
      yordamchiSoz: "nainki",
      turkumi: "yuklama",
      xalqaroTegi: "part",
      ozbekchaTegi: "yukl",
      sofvazifaDosh: "sof.yukl",
      shakli: "so'z shaklda",
      manoTuri: "kuchaytiruv-ta'kid",
      uslubiyXoslanishi: "badiiy",
      sofTurkumi: "",
      yordamchiSozVaOlinganManba: "Axir u yigirma yildan beri o'ziniki edi-ku, nainki shuncha muddat vujud-tanalari bir bo'lgan odamlar endi begonalarday, bir-biridan butunlay yiroqlashib ketishsa? Q.kenja, Toshqin.",
    },
    {
      yordamchiSoz: "natijasida",
      turkumi: "ko'makchi",
      xalqaroTegi: "post",
      ozbekchaTegi: "ko'm",
      sofvazifaDosh: "vaz.ko'm",
      shakli: "so'z shaklda",
      manoTuri: "sabab",
      uslubiyXoslanishi: "so'zlashuv",
      sofTurkumi: "ot",
      yordamchiSozVaOlinganManba: "Tunlari ko'p o'qishi natijasida ko'z pardalari xiralashib qoldi.",
    },
  ];
  return data;
}
